/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.14.v202311100605.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COMMONAPI_HELLO_WORLD_HPP_
#define V1_COMMONAPI_HELLO_WORLD_HPP_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Types.hpp>
#include <cstdint>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {

class HelloWorld {
public:
    virtual ~HelloWorld() { }

    static inline const char* getInterface();
    static inline CommonAPI::Version getInterfaceVersion();
    
    struct EventType : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            HEART_BEAT = 0,
            HB_RESTART = 1,
            RESET_REQUEST = 2
        };
    
        EventType()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::HEART_BEAT)) {}
        EventType(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::HEART_BEAT):
                case static_cast< uint8_t>(Literal::HB_RESTART):
                case static_cast< uint8_t>(Literal::RESET_REQUEST):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const EventType &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const EventType &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const EventType &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const EventType &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const EventType &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const EventType &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::HEART_BEAT): return "HEART_BEAT";
            case static_cast< uint8_t>(Literal::HB_RESTART): return "HB_RESTART";
            case static_cast< uint8_t>(Literal::RESET_REQUEST): return "RESET_REQUEST";
            default: return "UNDEFINED";
            }
        }
    };
};

const char* HelloWorld::getInterface() {
    return ("commonapi.HelloWorld:v1_0");
}

CommonAPI::Version HelloWorld::getInterfaceVersion() {
    return CommonAPI::Version(1, 0);
}


} // namespace commonapi
} // namespace v1

namespace CommonAPI {
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_HELLO_WORLD_HPP_
